// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Customer struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Address string `json:"address"`
	Email   string `json:"email"`
}

type Invoice struct {
	InvoiceNumber   int64     `json:"invoice_number"`
	IssueDate       time.Time `json:"issue_date"`
	DueDate         time.Time `json:"due_date"`
	OrderID         int64     `json:"order_id"`
	VendorName      string    `json:"vendor_name"`
	VendorPhone     string    `json:"vendor_phone"`
	VendorAddress   string    `json:"vendor_address"`
	VendorEmail     string    `json:"vendor_email"`
	CustomerName    string    `json:"customer_name"`
	CustomerPhone   string    `json:"customer_phone"`
	CustomerAddress string    `json:"customer_address"`
	CustomerEmail   string    `json:"customer_email"`
}

type Order struct {
	ID           int64  `json:"id"`
	CustomerID   int64  `json:"customer_id"`
	Status       string `json:"status"`
	Subtotal     int64  `json:"subtotal"`
	DiscountRate int32  `json:"discount_rate"`
	TotalAmount  int64  `json:"total_amount"`
	Note         string `json:"note"`
}

type OrdersItem struct {
	ID          int64  `json:"id"`
	OrderID     int64  `json:"order_id"`
	Description string `json:"description"`
	Quantity    int64  `json:"quantity"`
	UnitPrice   int64  `json:"unit_price"`
	TotalPrice  int64  `json:"total_price"`
}
